[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/',
    "forge-std/=lib/forge-std/src/"
]

[invariant]
runs  = 128
depth = 128
fail_on_revert=false


#here we defines the endpoints which we can pass while giving the commands
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/84957a0b5c6f43668c65a3cc65ac53ce"

#here we can define the etherscan-api for verification, by passing --verify parameter
[etherscan]
sepolia = { key = "E31XU9BEEEMVEPH7XRICNN2N7ASJQMXEI9" }
