[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink/contracts/'
]

#here we defines the endpoints which we can pass while giving the commands
[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/84957a0b5c6f43668c65a3cc65ac53ce"

#here we can define the etherscan-api for verification, by passing --verify parameter
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
